package com.synth.lover.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF904A47)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDAD7)
val onPrimaryContainerLight = Color(0xFF3B080A)
val secondaryLight = Color(0xFF8C4A60)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFD9E2)
val onSecondaryContainerLight = Color(0xFF3A071D)
val tertiaryLight = Color(0xFF8D4A5B)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD9E0)
val onTertiaryContainerLight = Color(0xFF3A0719)
val errorLight = Color(0xFF904A43)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF3B0907)
val backgroundLight = Color(0xFFFFF8F7)
val onBackgroundLight = Color(0xFF231919)
val surfaceLight = Color(0xFFFFF8F5)
val onSurfaceLight = Color(0xFF221A14)
val surfaceVariantLight = Color(0xFFF4DDDB)
val onSurfaceVariantLight = Color(0xFF534342)
val outlineLight = Color(0xFF857371)
val outlineVariantLight = Color(0xFFD8C1C0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF382F28)
val inverseOnSurfaceLight = Color(0xFFFEEEE4)
val inversePrimaryLight = Color(0xFFFFB3AF)
val surfaceDimLight = Color(0xFFE7D7CE)
val surfaceBrightLight = Color(0xFFFFF8F5)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1E9)
val surfaceContainerLight = Color(0xFFFBEBE1)
val surfaceContainerHighLight = Color(0xFFF5E5DC)
val surfaceContainerHighestLight = Color(0xFFEFDFD6)


val primaryDark = Color(0xFFFFB3AF)
val onPrimaryDark = Color(0xFF571D1D)
val primaryContainerDark = Color(0xFF733331)
val onPrimaryContainerDark = Color(0xFFFFDAD7)
val secondaryDark = Color(0xFFFFB1C8)
val onSecondaryDark = Color(0xFF541D32)
val secondaryContainerDark = Color(0xFF703349)
val onSecondaryContainerDark = Color(0xFFFFD9E2)
val tertiaryDark = Color(0xFFFFB1C2)
val onTertiaryDark = Color(0xFF551D2D)
val tertiaryContainerDark = Color(0xFF713343)
val onTertiaryContainerDark = Color(0xFFFFD9E0)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF561E19)
val errorContainerDark = Color(0xFF73332D)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1A1111)
val onBackgroundDark = Color(0xFFF1DEDD)
val surfaceDark = Color(0xFF19120D)
val onSurfaceDark = Color(0xFFEFDFD6)
val surfaceVariantDark = Color(0xFF534342)
val onSurfaceVariantDark = Color(0xFFD8C1C0)
val outlineDark = Color(0xFFA08C8B)
val outlineVariantDark = Color(0xFF534342)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEFDFD6)
val inverseOnSurfaceDark = Color(0xFF382F28)
val inversePrimaryDark = Color(0xFF904A47)
val surfaceDimDark = Color(0xFF19120D)
val surfaceBrightDark = Color(0xFF413731)
val surfaceContainerLowestDark = Color(0xFF140D08)
val surfaceContainerLowDark = Color(0xFF221A14)
val surfaceContainerDark = Color(0xFF261E18)
val surfaceContainerHighDark = Color(0xFF312822)
val surfaceContainerHighestDark = Color(0xFF3C332D)





